Atualização de calendário (tamanho/retirada de evento diário)
ISCTE-Eng-Software-GRUPO-B/ES-2023-2Sem-Grupo-B pull request #6
Opened 2023-04-18 22:06 UTC by nokinhas2002

Implementaç\ao de botoes submit, download JSON e CSV.

2023-04-18 22:07 UTC, Joao-Diogo-Figueirinha-Rodrigues submitted a review, later dismissed
De acordo com as alterações

2023-04-18 22:22 UTC, jmmpo3 requested changes

2023-04-18 22:22 UTC, jmmpo3 commented on src/main/resources/calendarioPortugues.js
>  (function($){
Este ficheiro deverá ser inserido numa pasta "scripts".

2023-04-18 22:22 UTC, jmmpo3 commented on src/main/resources/teste.html
>  <!DOCTYPE html>
Este ficheiro deverá ter o nome index.

2023-04-18 22:22 UTC, jmmpo3 commented on src/main/resources/teste.html
> +<body>
Nit: Identação.

2023-04-18 22:22 UTC, jmmpo3 commented on src/main/resources/teste.html
> +<form style="text-align: right">
Estilos devem ser extraídos para um ficheiro CSS.

2023-04-18 22:22 UTC, jmmpo3 commented on src/main/resources/teste.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
Scripts devem ser movidos para o final do body para carregar a página o mais rapidamente possivel.

2023-04-18 22:22 UTC, jmmpo3 commented on src/main/resources/teste.html
> +<form style="text-align: right">
Falta a action, podemos colocar já o seguinte url: "/calendar/download"

2023-04-19 00:37 UTC, jmmpo3 commented on src/main/resources/teste.html
> +    <input type="submit" id = "SUBMIT">
Botão deverá conter o texto "Download Calendar"

2023-04-19 00:39 UTC, jmmpo3 commented
Ainda que as alterações neste PR sejam necessárias a longo prazo o importante a curto prazo seria ter um form para fornecer o calendário à aplicação, seja via file seja via URL.

2023-04-19 18:12 UTC, nokinhas2002 commented on src/main/resources/teste.html
>  <!DOCTYPE html>
corrigido

2023-04-19 18:42 UTC, pmfpiresiscte approved these changes

2023-04-19 18:45 UTC, jmmpo3 approved these changes

2023-04-19 18:45 UTC, merged

2023-04-21 01:29 UTC, jmmpo3 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Representação do calendário em HTML](https://trello.com/c/oMdk30ps/6-representa%C3%A7%C3%A3o-do-calend%C3%A1rio-em-html)