Java endpoint to fetch URL (JSON or CSV)
ISCTE-Eng-Software-GRUPO-B/ES-2023-2Sem-Grupo-B pull request #7
Opened 2023-04-18 23:06 UTC by vasdd

Caros,
Vejam por favor se é esta a ideia para este endpoint.
Obg
Vasco

2023-04-19 00:32 UTC, jmmpo3 requested changes

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +    public String getFile(@RequestBody UrlFile request) throws IOException {
As classes de request e response dos controladores REST por convenção têm o sufixo "Request" e "Response" respetivamente.

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +    public String getFile(@RequestBody UrlFile request) throws IOException {
Extraía este método para um novo controlador à parte cujo nome poderá ser Calendar.

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +    @PostMapping(value = "/get-file-from-url")
`@PostMapping(path = "calendar/consume/url", consumes = MediaType.ALL_VALUE)`

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +     * Returns the json or csv file from the specified URL
Isto é a descrição do método, portanto: Receives a remote location (url) that contains calendar data, downloads and stores it.

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +     * @return          the file in specified url
@return the calendar in json format

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +       try (BufferedReader in =new BufferedReader(new InputStreamReader(url.openStream()))) {
Eu tentaria encapsular o download do ficheiro remoto numa classe separada.

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +           return output.toString();
Antes de retornar há que:
- Caso se trate de um JSON, tentar desserializar para um model `Calendar` de forma a podermos garantir que os campos necessários estão presentes e têm o formato expectável. (Ver `Jackson ObjectMapper`, lembra-me de te enviar um exemplo amanhã).
- Caso se trate de um CSV, tentar fazer o parse (via classe utilitária que o @lourencosoaress implementou).

Como parte desta lógica está dependente de outros tickets eu sugeria colocar um TODO com este texto como placeholder.

2023-04-19 00:32 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/model/UrlFile.java
> +    public enum UrlType {
Classe deve ser extraída para uma standalone uma vez que será reutilizada por outros models.
Sugiro também que se altere o nome para `CalendarType`, `CalendarStructure` ou `CalendarFormat`.

2023-04-19 00:41 UTC, jmmpo3 commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/model/UrlFile.java
> +public class UrlFile {
A minha sugestão seria ConsumeURLCalendarRequest.

2023-04-19 18:33 UTC, vasdd commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/controller/BackendController.java
> +    @PostMapping(value = "/get-file-from-url")
Vou alterar para MediaType.JSON

2023-04-19 21:53 UTC, Joao-Diogo-Figueirinha-Rodrigues approved these changes, later dismissed
De acordo com as alterações

2023-04-20 23:03 UTC, Joao-Diogo-Figueirinha-Rodrigues approved these changes, later dismissed
De acordo com as alterações

2023-04-20 23:27 UTC, jmmpo3 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar endpoint no JAVA que recebe um URL e faz download do ficheiro.](https://trello.com/c/HiCTH6ZY/44-criar-endpoint-no-java-que-recebe-um-url-e-faz-download-do-ficheiro)

2023-04-20 23:29 UTC, jmmpo3 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar endpoint no JAVA que recebe um URL e faz download do ficheiro.](https://trello.com/c/HiCTH6ZY/44-criar-endpoint-no-java-que-recebe-um-url-e-faz-download-do-ficheiro)

2023-04-20 23:32 UTC, jmmpo3 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar endpoint no JAVA que recebe um URL e faz download do ficheiro.](https://trello.com/c/HiCTH6ZY/44-criar-endpoint-no-java-que-recebe-um-url-e-faz-download-do-ficheiro)

2023-04-21 01:23 UTC, jmmpo3 approved these changes

2023-04-21 01:27 UTC, merged