Upload calendar via file
ISCTE-Eng-Software-GRUPO-B/ES-2023-2Sem-Grupo-B pull request #8
Opened 2023-04-19 01:45 UTC by jmmpo3

Acrescenta um controlador REST `CalendarController` com um único endpoint cuja funcionalidade é receber um ficheiro e convertê-lo para JSON caso não esteja, guardando-o em memória e retornando os conteúdos de seguida.

2023-04-19 18:07 UTC, jmmpo3 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar endpoint no JAVA para receber o ficheiro.](https://trello.com/c/Va6HXGHy/42-criar-endpoint-no-java-para-receber-o-ficheiro)

2023-04-19 18:23 UTC, pmfpiresiscte approved these changes, later dismissed

2023-04-19 21:51 UTC, nokinhas2002 approved these changes, later dismissed

2023-04-19 21:52 UTC, vasdd requested changes

2023-04-19 21:52 UTC, vasdd commented on src/main/java/com/iscte/engsoft/grupob/CalendarApp/model/FileType.java
Já temos esta class no meu branch (CalendarFormat)

2023-04-20 22:04 UTC, lourencosoaress approved these changes

2023-04-20 22:11 UTC, vasdd approved these changes
Nada a comentar

2023-04-20 23:12 UTC, merged